# Generated by Django 3.0.8 on 2020-07-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200707_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default-post.jpg', upload_to='post_pics'),
        ),
    ]
