# Generated by Django 3.0.8 on 2020-07-09 12:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='b', editable=False, populate_from='title'),
        ),
    ]
