# Generated by Django 3.0.8 on 2020-07-10 08:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200709_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='importance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
